name: Release
on:
  release:
    types: [published]
jobs:
  tracker:
    runs-on: ubuntu-latest
    env:
      OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
      ORG_ID: ${{ secrets.ORG_ID }}
    steps:
      - name: 'init'
        uses: actions/checkout@v2
          fetch-depth: 0

      - uses: actions/setup-node@v1
        name: 'setup node'
        with:
          node-version: '14'

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: 'create issue'
        run: bash ./scripts/issue.bash

      - name: 'run tests'
        run: bash ./scripts/tests.bash

      - name: 'docker'
        run: bash ./scripts/docker.bash
